### PR TITLE
fix: don't pass special properties to otel span attributes

### LINKED ISSUE #142: Special span properties leak into opentelemetry span tags
## Details
`fastrace-opentelemetry` has special property keys for setting otel span properties ([link to docs](https://github.com/fast/fastrace/blob/main/fastrace-opentelemetry/src/lib.rs#L51-L64)):
- span.kind
- span.status_code
- span.status_description

These properties set span_kind and span_status, but also are added to span's attributes. This results in tag duplication in Jaeger.

Image

## Reproduction

Cargo.toml
```toml
[package]
name = "fastrace-reproduce"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrace = { version = "0.7.14", features = ["enable"] }
fastrace-opentelemetry = {version = "0.14.0"}

opentelemetry = { version = "0.31.0", default-features = false, features = [
  "trace",
] }
opentelemetry-otlp = { version = "0.31.0", default-features = false, features = [
  "trace",
  "grpc-tonic",
] }
opentelemetry_sdk = { version = "0.31.0", default-features = false, features = [
  "trace",
] }

tokio = { version = "1.45.0", features = ["full"] }

```

main.rs

```rust
use fastrace::collector::Config;
use fastrace::prelude::*;
use fastrace_opentelemetry::OpenTelemetryReporter;
use opentelemetry::InstrumentationScope;
use opentelemetry::KeyValue;
use opentelemetry_otlp::SpanExporter;
use opentelemetry_otlp::WithExportConfig;
use opentelemetry_sdk::Resource;
use std::borrow::Cow;
use std::time::Duration;

#[tokio::main]
async fn main() {
    let reporter = OpenTelemetryReporter::new(
        SpanExporter::builder()
            .with_tonic()
            .with_endpoint("http://127.0.0.1:4317".to_string())
            .with_protocol(opentelemetry_otlp::Protocol::Grpc)
            .with_timeout(opentelemetry_otlp::OTEL_EXPORTER_OTLP_TIMEOUT_DEFAULT)
            .build()
            .expect("initialize oltp exporter"),
        Cow::Owned(
            Resource::builder()
                .with_attributes([KeyValue::new("service.name", "example")])
                .build(),
        ),
        InstrumentationScope::builder("example-crate")
            .with_version(env!("CARGO_PKG_VERSION"))
            .build(),
    );
    fastrace::set_reporter(reporter, Config::default());

    let ctx = SpanContext::random();
    let root = Span::root("root", ctx).with_properties(|| {
        [
            ("span.kind", "server"),
            ("span.status_code", "error"),
            ("span.status_description", "some error description"),
        ]
    });

    tokio::time::sleep(Duration::from_millis(100))
        .in_span(root)
        .await;

    fastrace::flush();
}

```

## Proposed fix
We could filter out these special otel properties before passing them to SpanData.

### PR DESCRIPTION
**Pull request by fedosiq**
Resolves #142

### CODE REVIEW

File: fastrace-opentelemetry/src/lib.rs [hunk 1]
```diff
@@ -152,7 +161,11 @@ impl OpenTelemetryReporter {
                         SystemTime::UNIX_EPOCH + Duration::from_nanos(begin_time_unix_ns);
                     let end_time = SystemTime::UNIX_EPOCH
                         + Duration::from_nanos(begin_time_unix_ns + duration_ns);
-                    let attributes = map_props_to_kvs(properties);
+                    let attributes = properties
+                        .into_iter()
+                        .filter(|(k, _)| !OTEL_PROPERTIES.contains(k.as_ref()))
```
Comment (andylokandy) [inline fastrace-opentelemetry/src/lib.rs]: Maybe move the filter into map_props_to_kvs?
